### ISSUE TITLE
going to .../profile/[a-z]* takes you to profile/1

### ISSUE THREAD

**Issue by HoloPollock** [GoodbyteCo/Bookplate-Frontend#1]

**Comment by qjack001** [comment]
What do you receive on the database? Are you returning a 404 if there are letters in the id? It takes me to your profile, rather than my own which is weird as well...

**Comment by HoloPollock** [comment]
yup it was on my end. Fixed however, I return 200 for reader/profile/[a-z]* as otherwise an alert is throw is that what you want?

**Comment by qjack001** [comment]
why not return a 404? as no profile could have that id?

**Comment by HoloPollock** [comment]
Yah I was going to do that but you have it throw an alert which isn’t a great experience

**Comment by qjack001** [comment]
no, if it's a 404 it redirects to the 404 page. It only sends an alert if its not a 404, 401, or 200 (and I'll probably get around to changing that eventually to something nicer)
